### ISSUE TITLE
Host documentation on readthedocs

### ISSUE THREAD

**Issue by Ayrx** [pyca/tls#33]
We have the Sphinx stuff setup already, we just need to link it to readthedocs. Not a pressing issue  but I'm filing this so we don't forget about it.

**Comment by ashfall** [comment]
We're almost there, thanks to @markrwilliams' #85. 
Possible next step: Figure out a URL for hosting the docs and link it from the README.

**Comment by ashfall** [comment]
Docs are now hosted at http://tls.readthedocs.io/en/latest/ 🎆
