### ISSUE TITLE
Add length limitations where necessary

### ISSUE THREAD

**Issue by radix** [pyca/tls#36]
There are a number of places with TODO comments about constraining the lengths (both minimum and maximum) of a field. Let's do it!

Ideally this should be done with a Construct class that encodes the constraints declaratively

**Comment by ashfall** [comment]
From #84, which I am now closing as a duplicate:

Some possible solutions discussed offline with @markrwilliams:

- Once we move to `TLSPrefixedArray` (#82), we could add in a range parameter
- We could write an Adapter that can wrap a `TLSPrefixedArray`
- We could write a Validator

**Comment by ashfall** [comment]
Fixed in #88
