### ISSUE TITLE
Reorganize code structure

### ISSUE THREAD

**Issue by Ayrx** [pyca/tls#72]
I propose that the project structure be reorganized. The main motivation for this is a problem I am facing when fixing #44. To use `Switch` I'll need to import `tls.message.HandshakeType` in `tls._construct` which causes a circular import problem.

I suggest that that we group all related objects (Enums, construct Structs, parsers) together in a single module instead of having `tls._construct`. This also makes the code easier to read and modify since related code will be grouped together instead of split up among several files.

@ashfall

**Comment by ashfall** [comment]
Thank you for working on this, apologies about the delay in responding. I believe that at present the codebase is small enough for there to not be too many complications due to reorganizing things. Can you make a PR with what you think will help with #44?

Thanks again!

**Comment by ashfall** [comment]
I think we can close this issue once the following tasks are completed:

- [ ] Move all enums to a single place. - #91 
- [ ] Rename and move `utils.py` to `_common`.
