### ISSUE TITLE
hypothesis for wire format testing

### ISSUE THREAD

**Issue by markrwilliams** [pyca/tls#81]
Right now the tests for the components that make up TLS' wire format exercise just a few cases.  That's great because it means the tests are comprehensible and fast.  But as `tls` the library supports more of TLS the protocol, it would be helpful to have an additional test suite that exercises many cases.

Property-based testing  compliments wire protocol development and [hypothesis](https://hypothesis.readthedocs.io) is a pretty great property-testing library.  `tls._constructs` should get some `hypothesis` tests!

**Comment by markrwilliams** [comment]
As discussed in #61, the TLS pseudo-random function is an excellent candidate for hypothesis tests.  We should write some!

**Comment by ashfall** [comment]
Some hypothesis tests were merged for the TLS PRF in #96.
